### ISSUE TITLE
Running console script with fresh install fails

### ISSUE THREAD

**Issue by shaunduncan** [shaunduncan/helga#134]
See this traceback:

```
Traceback (most recent call last):
  File "../../bin/helga", line 10, in <module>
    load_entry_point('helga==1.6.4', 'console_scripts', 'helga')()
  File "/opt/devel/rph/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/devel/rph/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/opt/devel/rph/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named bin.helga
```

**Comment by shaunduncan** [comment]
Fixed in 1.6.5. The helga/bin dir was missing __init__.py (Thanks .gitignore!)
