### ISSUE TITLE
XMPP client doesn't have operators

### ISSUE THREAD

**Issue by shaunduncan** [shaunduncan/helga#145]
```
2015-03-06 16:40:41,859 [ERROR] [helga.plugins:333]: Calling process on plugin <helga.plugins.Command object at 0x7f3311775690> failed
Traceback (most recent call last):
  File "/opt/helga/local/lib/python2.7/site-packages/helga/plugins/__init__.py", line 327, in process
    resp = plugin.process(client, channel, nick, message)
  File "/opt/helga/local/lib/python2.7/site-packages/helga/plugins/__init__.py", line 619, in process
    return self.run(client, channel, nick, message, command, args)
  File "/opt/helga/local/lib/python2.7/site-packages/helga/plugins/operator.py", line 70, in operator
    if nick not in client.operators:
AttributeError: 'Client' object has no attribute 'operators'
```

**Comment by shaunduncan** [comment]
Fixed in 1.7.1
